### ISSUE TITLE
funcat盘中计算指标问题

### ISSUE THREAD

**Issue by phoenixxz** [cedricporter/funcat#11]
funcat 0.2.7,python2.7 ,centos
测试代码如下：
from funcat.data.tushare_backend import TushareDataBackend
set_data_backend(TushareDataBackend())
T("20170704")
S("600030.XSHG")
print(O, H, L, C)
今天的时间就是20170704，正在盘中交易时间，取盘中交易数据，用的tushare的backend，可是仍旧会报错。
(Traceback (most recent call last):
  File "3.py", line 30, in <module>
    print(O, H, L, C)
  File "/usr/lib/python2.7/site-packages/funcat-0.2.7-py2.7.egg/funcat/time_series.py", line 205, in __repr__
    return str(self.value)
  File "/usr/lib/python2.7/site-packages/funcat-0.2.7-py2.7.egg/funcat/utils.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/funcat-0.2.7-py2.7.egg/funcat/time_series.py", line 79, in value
    raise FormulaException("DATA UNAVAILABLE")
funcat.utils.FormulaException: DATA UNAVAILABLE

目前不支持盘中取数据吗？

**Comment by phoenixxz** [comment]
>>> print ts.__version__
0.8.2
