### ISSUE TITLE
EMA() takes at most 2 positional arguments (3 given)

### ISSUE THREAD

**Issue by a5601564** [cedricporter/funcat#29]
# 提 ISSUE 须知
EMA() takes at most 2 positional arguments (3 given)

如果是 bug 反馈，烦请在 issue 中描述以下问题：

## 1. funcat 的版本

funcat==0.3.2
## 2. Python 的版本
3.6

## 3. 是 Windows / Linux / MacOS or others?
windows

## 4. 您出现问题对应的源码 / 或者能复现问题的简易代码
close_data = NumericSeries([1,2,3])
    EMA (close_data,3)
## 5. 您出现的错误堆栈日志信息
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\lib\site-packages\funcat-0.3.2-py3.6.egg\funcat\func.py", line 31, in __init__
    series = self.func(series, arg)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\talib\__init__.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "_func.pxi", line 7053, in talib._ta_lib.EMA
TypeError: EMA() takes at most 2 positional arguments (3 given)

**Comment by ksgt00857912** [comment]
我也出现这个问题了 怎么解决呀？

**Comment by ljk99** [comment]
talib的版本要用回4.1.7，更新以后的4.1.8出错
