### ISSUE TITLE
数据格式转换问题

### ISSUE THREAD

**Issue by Tipsyume** [cedricporter/funcat#36]
refuncat:版本0.3.3
python:版本3.7.4
Mac：
相关代码：

`backend = "tushare"

if backend == "rqalpha":
    set_data_backend(RQAlphaDataBackend("~/.rqalpha/bundle"))
elif backend == "tushare":
    set_data_backend(TushareDataBackend())

set_start_date("2019-10-09")
S("002668.XSHG")  # 设置当前关注股票
T("2019-10-10")   # 设置当前观察日期

M1, M2 = 14, 6
OPEN = 10.0
HIGH = 10.5
LOW = 9.7
CLOSE = 10.2

TR = SUM(MAX(MAX(HIGH - LOW, ABS(HIGH - REF(CLOSE, 1))), ABS(LOW - REF(CLOSE, 1))), M1)
HD = HIGH - REF(HIGH, 1)
LD = REF(LOW, 1) - LOW

DMP = SUM(IF((HD > 0) & (HD > LD), HD, 0), M1)
DMM = SUM(IF((LD > 0) & (LD > HD), LD, 0), M1)
DI1 = DMP * 100 / TR
DI2 = DMM * 100 / TR
ADX = MA(ABS(DI2 - DI1) / (DI1 + DI2) * 100, M2)
ADXR = (ADX + REF(ADX, M2)) / 2

print(str(DI1),str(DI2), str(ADX), str(ADXR))`

错误日志：

`
Traceback (most recent call last):
  File "/Users/apple/PycharmProjects/h_Python/example/strategy/stock_formula.py", line 23, in <module>
    TR = SUM(MAX(MAX(HIGH - LOW, ABS(HIGH - REF(CLOSE, 1))), ABS(LOW - REF(CLOSE, 1))), M1)
  File "/Users/apple/PycharmProjects/h_Python/venv/lib/python3.7/site-packages/funcat/func.py", line 190, in Ref
    return s1[n]
TypeError: 'float' object is not subscriptable`

**Comment by Tipsyume** [comment]
ok了，是我这边传的数据有问题。
