### ISSUE TITLE
运行中的问题

### ISSUE THREAD

**Issue by phoenixxz** [cedricporter/funcat#9]
from funcat.data.tushare_backend import TushareDataBackend
from funcat import *

set_data_backend(TushareDataBackend())

T('20170704')
S('000001.XSHG')
print BIAS(L1=5, L4=10, L5=20)

[root@iz2zei55e7v33zfioqrugdz back_track]# python 3.py 
Traceback (most recent call last):
  File "3.py", line 19, in <module>
    print BIAS(L1=5, L4=10, L5=20)
  File "/usr/lib/python2.7/site-packages/funcat-0.2.7-py2.7.egg/funcat/indicators.py", line 89, in BIAS
    BIAS = (CLOSE - MA(CLOSE, L1)) / MA(CLOSE, L1) * 100
  File "/usr/lib/python2.7/site-packages/funcat-0.2.7-py2.7.egg/funcat/func.py", line 33, in __init__
    raise FormulaException(e)
funcat.utils.FormulaException: inputs are all NaN

**Comment by phoenixxz** [comment]
BIAS可以计算盘中的值吗？

**Comment by phoenixxz** [comment]
select(
    lambda : C / C[1] - 1 >= 0.0995,
    start_date=20161231,
	end_date=20170104,
)运行结束以后总有一个kill的，python程序被结束，如何才能不用killed，让程序继续进行？

**Comment by cedricporter** [comment]
盘中计算看 #4 最后有讨论。

另外跑完停不停止这个看你的程序怎么写的啊 -。-
